src/Entity/Bike.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BikeRepository")
 */
class Bike
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="2", max="255", minMessage="foo")
     */
    private $brand;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $model;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $matriculation;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $color;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     * @Assert\NotBlank()
     */
    private $power;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $km;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank()
     */
    private $productionYear;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     */
    private $createAt;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", inversedBy="bikes")
     */
    private $tags;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\BikeOwner", mappedBy="bike", cascade={"persist", "remove"})
     */
    private $bikeOwner;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="bike")
     */
    private $reservations;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getBrand() . " " . $this->getModel() . " (" . $this->getMatriculation() . ")";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getMatriculation(): ?string
    {
        return $this->matriculation;
    }

    public function setMatriculation(string $matriculation): self
    {
        $this->matriculation = $matriculation;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getPower()
    {
        return $this->power;
    }

    public function setPower($power): self
    {
        $this->power = $power;

        return $this;
    }

    public function getKm(): ?int
    {
        return $this->km;
    }

    public function setKm(?int $km): self
    {
        $this->km = $km;

        return $this;
    }

    public function getProductionYear(): ?\DateTimeInterface
    {
        return $this->productionYear;
    }

    public function setProductionYear(\DateTimeInterface $productionYear): self
    {
        $this->productionYear = $productionYear;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * @return string
     */
    public function getStatusTransKey(): string
    {
        $status = $this->getStatus();

        if($status == 1){
            return 'bike.entity.status.available.label';
        } elseif ($status == 2){
            return 'bike.entity.status.unavailable.label';
        } elseif ($status == 3){
            return 'bike.entity.status.repair.label';
        } elseif ($status == 4){
            return 'bike.entity.status.crashed.label';
        } else {
            return 'bike.entity.status.default.label';
        }
    }



    public function setStatus(?int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    public function getBikeOwner(): ?BikeOwner
    {
        return $this->bikeOwner;
    }

    public function setBikeOwner(?BikeOwner $bikeOwner): self
    {
        $this->bikeOwner = $bikeOwner;

        // set (or unset) the owning side of the relation if necessary
        $newBike = $bikeOwner === null ? null : $this;
        if ($newBike !== $bikeOwner->getBike()) {
            $bikeOwner->setBike($newBike);
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setBike($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getBike() === $this) {
                $reservation->setBike(null);
            }
        }

        return $this;
    }
}

src/Form/BikeType.php
<?php

namespace App\Form;

use App\Entity\Bike;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BikeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('brand')
            ->add('model')
            ->add('matriculation')
            ->add('color')
            ->add('power')
            ->add('km')
            ->add('productionYear', DateType::class, [
                'widget' => 'choice',
                'input_format' => 'Y',
                'years' => range('1970', date('Y'),1),
            ])
            ->add('status', ChoiceType::class, [
                'choices' => [
                    'bike.entity.status.available.label' => 1,
                    'bike.entity.status.unavailable.label' => 2,
                    'bike.entity.status.repair.label' => 3,
                    'bike.entity.status.crashed.label' => 4,
                ],
            ])
            ->add('tags')
            ->add('bikeOwner')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Bike::class,
            'attr' => [
                'novalidate' => 'novalidate',
            ]
        ]);
    }
}

src/Controller/BikeController.php
<?php

namespace App\Controller;

use App\Entity\Bike;
use App\Form\BikeType;
use App\Repository\BikeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/bike")
 */
class BikeController extends AbstractController
{
    /**
     * @Route("/", name="bike_index", methods={"GET"})
     */
    public function index(BikeRepository $bikeRepository): Response
    {
        return $this->render('bike/index.html.twig', [
            'bikes' => $bikeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="bike_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $bike = new Bike();
        $bike->setCreateAt(new \DateTime());
        $form = $this->createForm(BikeType::class, $bike);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($bike);
            $entityManager->flush();

            return $this->redirectToRoute('bike_index');
        }

        return $this->render('bike/new.html.twig', [
            'bike' => $bike,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bike_show", methods={"GET"})
     */
    public function show(Bike $bike): Response
    {
        return $this->render('bike/show.html.twig', [
            'bike' => $bike,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="bike_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Bike $bike): Response
    {
        $form = $this->createForm(BikeType::class, $bike);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('bike_index');
        }

        return $this->render('bike/edit.html.twig', [
            'bike' => $bike,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bike_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Bike $bike): Response
    {
        if ($this->isCsrfTokenValid('delete'.$bike->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($bike);
            $entityManager->flush();
        }

        return $this->redirectToRoute('bike_index');
    }

    /**
     * @Route("/status/{status_number}", name="bike_list_status", methods={"GET"})
     */
    public function listByStatus(BikeRepository $bikeRepository, int $status_number): Response
    {


        return $this->render('bike/index.html.twig', [
            'bikes' => $bikeRepository->findByStatus($status_number),
        ]);
    }
}

templates/bike/_delete_form.html.twig
<form method="post" action="{{ path('bike_delete', {'id': bike.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bike.id) }}">
    <button class="btn">Delete</button>
</form>

templates/bike/_form.html.twig
{{ form_start(form) }}
   {{ form_row(form.brand) }}
   {{ form_row(form.model) }}
   {{ form_row(form.matriculation) }}
   {{ form_row(form.color) }}
   {{ form_row(form.power) }}
   {{ form_row(form.km) }}
   {{ form_row(form.productionYear.year) }}
   {{ form_row(form.productionYear.month, { 'label':false,'attr': {'style': 'display:none'} }) }}
   {{ form_row(form.productionYear.day, { 'label':false,'attr': {'style': 'display:none'} }) }}
   {{ form_row(form.status) }}
   {{ form_row(form.tags) }}
   {{ form_row(form.bikeOwner) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/bike/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Bike{% endblock %}

{% block body %}
    <h1>Edit Bike</h1>

    {{ include('bike/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('bike_index') }}">back to list</a>

    {{ include('bike/_delete_form.html.twig') }}
{% endblock %}

templates/bike/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bike index{% endblock %}

{% block body %}
    <h1>Bike index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Brand</th>
                <th>Model</th>
                <th>Matriculation</th>
                <th>Color</th>
                <th>Power</th>
                <th>Km</th>
                <th>ProductionYear</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for bike in bikes %}
            <tr>
                <td>{{ bike.id }}</td>
                <td>{{ bike.brand }}</td>
                <td>{{ bike.model }}</td>
                <td>{{ bike.matriculation }}</td>
                <td>{{ bike.color }}</td>
                <td>{{ bike.power }}</td>
                <td>{{ bike.km }}</td>
                <td>{{ bike.productionYear ? bike.productionYear|date('Y') : '' }}</td>
                <td>{{ bike.statusTransKey|trans }}</td>
                <td>
                    <a href="{{ path('bike_show', {'id': bike.id}) }}">show</a>
                    <a href="{{ path('bike_edit', {'id': bike.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('bike_new') }}">Create new</a>
{% endblock %}

templates/bike/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'bike.new.title.label'|trans }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8">
                <h1>{{ 'bike.new.title.label'|trans }}</h1>
            </div>
            <div class="col-12 col-md-8">
                {{ include('bike/_form.html.twig') }}
            </div>
        </div>
    </div>




    <a href="{{ path('bike_index') }}">back to list</a>
{% endblock %}

templates/bike/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bike{% endblock %}

{% block body %}
    <h1>Bike</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ bike.id }}</td>
            </tr>
            <tr>
                <th>Brand</th>
                <td>{{ bike.brand }}</td>
            </tr>
            <tr>
                <th>Model</th>
                <td>{{ bike.model }}</td>
            </tr>
            <tr>
                <th>Matriculation</th>
                <td>{{ bike.matriculation }}</td>
            </tr>
            <tr>
                <th>Color</th>
                <td>{{ bike.color }}</td>
            </tr>
            <tr>
                <th>Power</th>
                <td>{{ bike.power }}</td>
            </tr>
            <tr>
                <th>Km</th>
                <td>{{ bike.km }}</td>
            </tr>
            <tr>
                <th>ProductionYear</th>
                <td>{{ bike.productionYear ? bike.productionYear|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ bike.status }}</td>
            </tr>
            <tr>
                <th>CreateAt</th>
                <td>{{ bike.createAt ? bike.createAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('bike_index') }}">back to list</a>

    <a href="{{ path('bike_edit', {'id': bike.id}) }}">edit</a>

    {{ include('bike/_delete_form.html.twig') }}
{% endblock %}