src/Entity/BikeOwner.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BikeOwnerRepository")
 */
class BikeOwner extends Person
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Bike", inversedBy="bikeOwner", cascade={"persist", "remove"})
     */
    private $bike;

    public function __toString(): ?string
    {
        return $this->getFirstName() . " " . $this->getLastName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBike(): ?Bike
    {
        return $this->bike;
    }

    public function setBike(?Bike $bike): self
    {
        $this->bike = $bike;

        return $this;
    }
}

src/Entity/Person.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/** @ORM\MappedSuperclass() */
class Person
{
    /**
     * @ORM\Column(type="smallint")
     */
    private $gender;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="2",max="255")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="2",max="255")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="2",max="255")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="2",max="255")
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="2",max="255")
     */
    private $postalCode;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="2",max="255")
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(min="2",max="255")
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(min="2",max="255")
     */
    private $bithDate;

    /**
     * @ORM\Column(type="date")
     */
    private $createdAt;

    public function getGender(): ?int
    {
        return $this->gender;
    }

    /**
     * @return string
     */
    public function getGenderTransKey(): string
    {
        $gender = $this->getGender();

        if($gender == 1){
            return 'person.gender.male.label';
        } elseif ($gender == 2){
            return 'person.gender.female.label';
        } elseif ($gender == 3){
            return 'person.gender.apache_copter.label';
        } elseif ($gender == 4){
            return 'person.gender.other.label';
        } else {
            return 'person.gender.unknown.label';
        }
    }

    public function setGender(int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getBithDate(): ?string
    {
        return $this->bithDate;
    }

    public function setBithDate(?string $bithDate): self
    {
        $this->bithDate = $bithDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Form/BikeOwnerType.php
<?php

namespace App\Form;

use App\Entity\BikeOwner;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BikeOwnerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('gender', ChoiceType::class, [
                'choices' => [
                    'person.gender.male.label' => 1,
                    'person.gender.female.label' => 2,
                    'person.gender.apache_copter.label' => 3,
                    'person.gender.other.label' => 4,
                ],
            ])
            ->add('firstName')
            ->add('lastName')
            ->add('address')
            ->add('city')
            ->add('postalCode')
            ->add('mail')
            ->add('phone')
            ->add('bithDate')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => BikeOwner::class,
        ]);
    }
}

src/Controller/BikeOwnerController.php
<?php

namespace App\Controller;

use App\Entity\BikeOwner;
use App\Form\BikeOwnerType;
use App\Repository\BikeOwnerRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/bike-owner")
 * @IsGranted("ROLE_ADMIN")
 */
class BikeOwnerController extends AbstractController
{
    /**
     * @Route("/", name="bike_owner_index", methods={"GET"})
     */
    public function index(BikeOwnerRepository $bikeOwnerRepository): Response
    {
        return $this->render('bike_owner/index.html.twig', [
            'bike_owners' => $bikeOwnerRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="bike_owner_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $bikeOwner = new BikeOwner();
        $bikeOwner->setCreatedAt(new \DateTime);
        $form = $this->createForm(BikeOwnerType::class, $bikeOwner);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($bikeOwner);
            $entityManager->flush();

            return $this->redirectToRoute('bike_owner_index');
        }

        return $this->render('bike_owner/new.html.twig', [
            'bike_owner' => $bikeOwner,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bike_owner_show", methods={"GET"})
     */
    public function show(BikeOwner $bikeOwner): Response
    {
        return $this->render('bike_owner/show.html.twig', [
            'bike_owner' => $bikeOwner,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="bike_owner_edit", methods={"GET","POST"})
     * @IsGranted("ROLE_SUPER_ADMIN")
     */
    public function edit(Request $request, BikeOwner $bikeOwner): Response
    {
        $form = $this->createForm(BikeOwnerType::class, $bikeOwner);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('bike_owner_index');
        }

        return $this->render('bike_owner/edit.html.twig', [
            'bike_owner' => $bikeOwner,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="bike_owner_delete", methods={"DELETE"})
     * @IsGranted("ROLE_SUPER_ADMIN")
     */
    public function delete(Request $request, BikeOwner $bikeOwner): Response
    {
        if ($this->isCsrfTokenValid('delete'.$bikeOwner->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($bikeOwner);
            $entityManager->flush();
        }

        return $this->redirectToRoute('bike_owner_index');
    }
}

templates/bike_owner/_delete_form.html.twig
<form method="post" action="{{ path('bike_owner_delete', {'id': bike_owner.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ bike_owner.id) }}">
    <button class="btn">Delete</button>
</form>

templates/bike_owner/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/bike_owner/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit BikeOwner{% endblock %}

{% block body %}
    <h1>Edit BikeOwner</h1>

    {{ include('bike_owner/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('bike_owner_index') }}">back to list</a>

    {{ include('bike_owner/_delete_form.html.twig') }}
{% endblock %}

templates/bike_owner/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}BikeOwner index{% endblock %}

{% block body %}
    <h1>BikeOwner index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Gender</th>
                <th>FirstName</th>
                <th>LastName</th>
                <th>Address</th>
                <th>City</th>
                <th>PostalCode</th>
                <th>Mail</th>
                <th>Phone</th>
                <th>BithDate</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for bike_owner in bike_owners %}
            {% dump bike_owner %}
            <tr>
                <td>{{ bike_owner.id }}</td>
                <td>{{ bike_owner.genderTransKey|trans }}</td>
                <td>{{ bike_owner.firstName }}</td>
                <td>{{ bike_owner.lastName }}</td>
                <td>{{ bike_owner.address }}</td>
                <td>{{ bike_owner.city }}</td>
                <td>{{ bike_owner.postalCode }}</td>
                <td>{{ bike_owner.mail }}</td>
                <td>{{ bike_owner.phone }}</td>
                <td>{{ bike_owner.bithDate }}</td>

                <td>
                    <a href="{{ path('bike_owner_show', {'id': bike_owner.id}) }}">show</a>
                    <a href="{{ path('bike_owner_edit', {'id': bike_owner.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('bike_owner_new') }}">Create new</a>
{% endblock %}

templates/bike_owner/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New BikeOwner{% endblock %}

{% block body %}
    <h1>Create new BikeOwner</h1>

    {{ include('bike_owner/_form.html.twig') }}

    <a href="{{ path('bike_owner_index') }}">back to list</a>
{% endblock %}

templates/bike_owner/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BikeOwner{% endblock %}

{% block body %}
    <h1>BikeOwner</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Gender</th>
                <td>{{ bike_owner.gender }}</td>
            </tr>
            <tr>
                <th>FirstName</th>
                <td>{{ bike_owner.firstName }}</td>
            </tr>
            <tr>
                <th>LastName</th>
                <td>{{ bike_owner.lastName }}</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>{{ bike_owner.address }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ bike_owner.city }}</td>
            </tr>
            <tr>
                <th>PostalCode</th>
                <td>{{ bike_owner.postalCode }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ bike_owner.mail }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ bike_owner.phone }}</td>
            </tr>
            <tr>
                <th>BithDate</th>
                <td>{{ bike_owner.bithDate }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ bike_owner.createdAt ? bike_owner.createdAt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Id</th>
                <td>{{ bike_owner.id }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('bike_owner_index') }}">back to list</a>

    {% if is_granted('ROLE_SUPER_ADMIN') %}
        <a href="{{ path('bike_owner_edit', {'id': bike_owner.id}) }}">edit</a>

        {{ include('bike_owner/_delete_form.html.twig') }}
    {% endif %}
{% endblock %}